#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd

# read csv file to create DataFrame sheet
df = pd.read_csv("All RNC Associations.xlsx", skip_blank_lines=False)


df1.to_excel("output.xlsx")  # doctest: +SKIP
